# Veille 2: Prise en main de la librairie Numpy

#### NumPy est une bibliothèque fondamentale sur laquelle reposent la plupart des bibliothèques de traitement de données Python largement utilisées (pandas, OpenCV), inspirées de (PyTorch) ou avec lesquelles elles peuvent partager efficacement des données (TensorFlow, Keras, etc.).

Le concept central de NumPy est un tableau à n dimensions. La beauté de cela est que la plupart des opérations se ressemblent, quel que soit le nombre de dimensions d'un tableau. Mais les cas 1D et 2D sont un peu particuliers. L'article est composé de trois parties :
1. Vecteurs, les tableaux à une (1) dimension
2. Matrices, les tableaux à deux (2) dimensions
3. A 3 dimensions et plus

## Tableau Numpy vs liste Python

In [306]:
import pandas as pd

In [1]:
#Avec les listes
a = [1,2,3]
[q*2 for q in a]

[2, 4, 6]

In [2]:
#Avec NumPy
import numpy as np
a = np.array([1,2,3])
a*2


array([2, 4, 6])

In [4]:
#Avec les listes
a = [1,2,3]
b = [4,5,6]
[q+r for q, r in zip(a,b)]

[5, 7, 9]

In [2]:
#Avec NumPy
import numpy as np
a = np.array([1.0,2.0,3.0,5.0])
b = np.array([4,5,6,4])
print(a+b)


[5. 7. 9. 9.]


## Quelques caractéristiques des tableaux NumPy :

- Plus compact, surtout lorsqu'il y a plus d'une dimension
-  Plus rapide que les listes lorsque l'opération peut être vectorisée
- Plus lent que les listes lorsque vous ajoutez des éléments à la fin
- Généralement homogène : ne peut fonctionner rapidement qu'avec des éléments d'un seul type

### Quelques signification :
- O(N) signifie que le temps nécessaire pour terminer l'opération est proportionnel à la taille du tableau.
- O*(1) (le O(1) dit « amorti » ) signifie que le temps ne dépend généralement pas de la taille du tableau 

## 1. Vecteurs, les tableaux à une (1) dimension

##### Initialisation vectorielle
Une façon de créer un tableau NumPy consiste à convertir une liste Python. Le type sera automatiquement déduit des types d'éléments de la liste.

### - fonction dtype :
Elle permet de déterminer le type d'une donnée.

In [27]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [28]:
b = np.array([1.,2.,3.])
b.dtype

dtype('float64')

### - fonction shape :
Elle permet de déterminer la taille d'un tableau.

In [29]:
b = np.array([1.,2.,3.,0.0,5.6])
b.shape

(5,)

### - Preallocation d'espace : Tableau Numpy
#### - Quelques fonctions utiles :
- zeros()
- empty()
###### Elles permettent d'allouer l'espace necessaire passé en premier paramètre tout en donnant le type de donnée en second paramètre 

In [34]:
b = np.zeros(5,float)
b

array([0., 0., 0., 0., 0.])

In [37]:
b = np.empty(5,float)
b

array([0., 0., 0., 0., 0.])

### - fonction zeros_like() :
Elle permet de créer un tableau vide qui corresponde à celui existant par forme et type d'éléments.

In [111]:
c = np.zeros_like(b)
c

array([0, 0, 0])

### - Remarque : 
Toutes les fonctions qui créent un tableau rempli d'une valeur constante ont une contrepartie _like.
On distingue : 
- zeros() -> zeros_like()
- ones() -> ones_like()
- empty() -> empty_like()
- full() -> full_like(), prend 2 paramètres, le premier est pour la taille du tableau et le second initialise le tableau en une variable donnée.

In [51]:
a = np.array([1,2,3])

In [52]:
# Cré un tableau de réel à une (1) dimension de taille 3 contenant que 0.0
np.zeros(3)

array([0., 0., 0.])

In [53]:
# Initialise le tableau a en une même dimension et même taille contenant que des entiers (0)
np.zeros_like(a)

array([0, 0, 0])

In [85]:
b = np.array([4,5,6])

In [54]:
# Cré un tableau de réel à une dimension de taille 3 contenant que des 1.0
np.ones(3)

array([1., 1., 1.])

In [60]:
# Initialise le tableau b en une même dimension et même taille contenant que des entiers (1)
np.ones_like(b)

array([1, 1, 1])

In [87]:
c = np.array([7,8,9])

In [88]:
# Cré un tableau de réel à une dimension de taille 3 contenant que 1.0
np.empty(3)

array([1., 1., 1.])

In [89]:
# Reproduit le même tableau c en une même dimension et même taille contenant les mêmes éléments
np.empty_like(c)

array([7, 8, 9])

In [92]:
d = np.array([10,11,12])

In [93]:
# Cré un tableau de réel à une dimension de taille 3 contenant que 7.0
np.full(3, 5.)

array([5., 5., 5.])

In [96]:
# Initialise le tableau d en une même dimension et même taille contenant que la variable passé en paramètre.
np.full_like(d, 8)

array([8, 8, 8])

##### Il existe jusqu'à deux fonctions pour l'initialisation d'un tableau avec une séquence monotone dans NumPy : 
On a la fonction arange() et la fonction linspace().

### - fonction arange() :
Elle permet de créer un tableau tout en passant en paramètre le debut, la fin et le pas (np.arange(debut, fin, pas)).
Elle exclut la valeur maximale à moins qu'une erreur d'arrondi n'en fasse autrement (avec les flottants).
Elle est surtout utilisé pour créer un tableau d'entiers.


In [101]:
np.arange(2, 15, 3)

array([ 2,  5,  8, 11, 14])

### - fonction linspace() :
Elle permet de créer un tableau tout en passant en paramètre le debut, la fin et le nombre d'étape (np.arange(debut, fin, nb_etape)).
Elle permet de définir le nombre de valeurs que vous obtenez, y compris les valeurs min et max spécifiées.
On peut ne pas lui passé un 3ème paramètre, dans ce cas elle générera un tableau de réel automatiquement.

In [109]:
np.linspace(3, 15, 4)

array([ 3.,  7., 11., 15.])

In [110]:
np.linspace(3, 15, )

array([ 3.        ,  3.24489796,  3.48979592,  3.73469388,  3.97959184,
        4.2244898 ,  4.46938776,  4.71428571,  4.95918367,  5.20408163,
        5.44897959,  5.69387755,  5.93877551,  6.18367347,  6.42857143,
        6.67346939,  6.91836735,  7.16326531,  7.40816327,  7.65306122,
        7.89795918,  8.14285714,  8.3877551 ,  8.63265306,  8.87755102,
        9.12244898,  9.36734694,  9.6122449 ,  9.85714286, 10.10204082,
       10.34693878, 10.59183673, 10.83673469, 11.08163265, 11.32653061,
       11.57142857, 11.81632653, 12.06122449, 12.30612245, 12.55102041,
       12.79591837, 13.04081633, 13.28571429, 13.53061224, 13.7755102 ,
       14.02040816, 14.26530612, 14.51020408, 14.75510204, 15.        ])

### - fonction random() :
Elle permet de générer des tableaux aléatoires. Il en exite : 

#### - La fonction random.randint() : 
Elle prend 3 paramètres et permet de générer un tableau aléatoire d'entier : np.random.randint(debut, fin, nombre_de chiffre_entre_debut_fin)

In [139]:
np.random.randint(0, 50, 100)

array([ 5, 15, 18, 20, 15, 18, 18, 24,  1,  0, 35, 39,  8,  4, 30, 25,  3,
       26, 34, 25, 18, 35, 28, 37,  9, 29,  3, 11, 19,  1,  3,  8,  8,  9,
       29, 15, 38, 48,  1,  0, 27, 25,  5, 24, 12,  0, 40, 42, 37, 10, 15,
        7,  1, 40, 28, 20, 24, 37, 25, 40, 18, 33,  8, 47, 14, 23, 41, 30,
       29, 41, 23,  7, 44, 42, 33,  0, 20, 29, 39, 26, 47, 31,  4, 21, 42,
       31, 39,  9, 25, 17, 34, 18, 36, 10, 17, 14, 12, 20, 47, 19])

#### - La fonction random.rand() : 
Elle prend 1 paramètre et permet de générer un tableau aléatoire de réel compris entre [0, 1] : np.random.rand(taille_tableau)

In [134]:
np.random.rand(7)

array([0.85548992, 0.45446359, 0.15506042, 0.57739044, 0.40516275,
       0.73819698, 0.0077023 ])

#### - La fonction random.randn() : 
Elle prend 1 paramètre et permet de générer un tableau aléatoire de réel négatif ou positif : np.random.randn(taille_tableau)

In [137]:
np.random.randn(5)

array([-0.66602909,  0.18673709, -1.36894216, -0.77820593, -0.50200695])

#### - La fonction random.uniform() : 
Elle prend 3 paramètres et permet de générer un tableau aléatoire de réel compris entre le min et le max du tableau et tous les deux inclus : np.random.uniform(debut, fin, nombre_de chiffre_entre_debut_fin)

In [142]:
np.random.uniform(1, 30, 50)

array([15.36083155, 17.1938518 , 17.85640537, 16.28254119, 24.97351206,
       12.66679954,  3.48992437, 13.38387986,  9.53726017, 26.70908248,
        8.5732048 ,  7.96494029, 12.96874114, 14.04926132, 12.9259246 ,
        8.01027122, 13.42419612, 21.8279461 ,  8.93619995,  6.81400017,
       16.29487989, 21.74575155, 23.97825279, 27.39862947, 25.19112031,
        8.90630099, 14.09243285,  1.96702547, 19.38639327,  2.77131323,
       26.71460613,  1.70993688, 15.59779167, 23.88270855, 12.33814709,
       12.50657814, 11.1039969 , 11.62738107,  3.98203133,  3.09941983,
       10.69836564,  8.28401198,  2.49753299, 19.33372866, 26.64317713,
       15.85199058, 13.88873694,  8.61630354, 20.82352266, 16.02877696])

#### - La fonction random.normal() : 
Elle prend 3 paramètres et permet de générer un tableau aléatoire de réel : np.random.normal(moyenne, ecart_type, taille_tableau)

In [149]:
np.random.normal(8, 4, size=(2, 3))
#np.random.normal(size=(2, 3))

array([[ 3.55163512, 12.54148262,  7.19923881],
       [13.32847803,  4.32043048, -0.19986943]])

#### - NB : 
##### Il existe également une nouvelle interface pour la génération de tableaux aléatoires (ci-dessous). Il est : 
##### > Mieux adapté au multi-threading
##### > Un peu plus rapide
##### > Plus configurable 
##### > Capable de passer deux tests synthétiques délicats que l'ancienne version échoue.


In [153]:
rng = np.random.default_rng(45)

In [156]:
rng.random(10)

array([0.05488732, 0.11987991, 0.70230947, 0.04407558, 0.70020679,
       0.41987544, 0.36937176, 0.15392513, 0.10637131, 0.12538958])

In [158]:
rng.uniform(2, 10, 20)

array([4.98661049, 2.28353946, 5.96329664, 3.62023971, 2.99464608,
       9.93994526, 4.86748979, 7.53756994, 3.68255885, 2.10856223,
       9.79808851, 7.78653384, 7.6572234 , 8.54728598, 4.55304202,
       5.49045492, 4.99950801, 8.99431163, 4.52789617, 4.72444167])

In [160]:
rng.normal(5, 2, 3)

array([6.98028342, 4.39709788, 5.38671864])

In [165]:
#Même fonction que rng.random() mais de moyenne = 0 et d'écart-type = 1
rng.standard_normal(5)

array([-1.26072181,  0.99830614, -0.65722162,  0.28175016,  0.93672138])

### 1.1 Indexation vectorielle
Il en existe plusieurs manières :

In [168]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
a[1]

2

In [170]:
a[2:6]

array([3, 4, 5, 6])

In [171]:
a[-2:]

array([8, 9])

In [174]:
a[2:4] = 0

In [175]:
a

array([1, 2, 0, 0, 5, 6, 7, 8, 9])

In [178]:
a[1:3] = [3, 4]
a

array([1, 3, 4, 0, 5, 6, 7, 8, 9])

#### - Fonction de copy des données : 

In [180]:
b = a.copy()
b

array([1, 3, 4, 0, 5, 6, 7, 8, 9])

#### - L'indexation booléenne : 

In [426]:
a = np.arange(1, 14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [428]:
print("Essai_1 :",a[3])
print("Essai_2 :",a[3:4])
print("Essai_3 :",a[3:])
print("Essai_4 :",a[::3]) #a[debut:fin:pas]
print("Essai_5 :",a[-2:])
print("Essai_6 :",a[[1, 3, 5]])

Essai_1 : 4
Essai_2 : [4]
Essai_3 : [ 4  5  6  7  8  9 10 11 12 13]
Essai_4 : [ 1  4  7 10 13]
Essai_5 : [12 13]
Essai_6 : [2 4 6]


In [240]:
a[7:12] = [6,5,4,3,2]
a[12] = 1
a
#b = a.copy()

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [200]:
a>5

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False])

In [201]:
np.any(a>5)

True

In [202]:
np.all(a>5)

False

In [203]:
a[a>5]

array([6, 7, 6])

In [205]:
a[a>5] = 0
a

array([1, 2, 3, 4, 5, 0, 0, 0, 5, 4, 3, 2, 1])

In [210]:
a[5:8] = [6, 7, 6]
a[(a>=3) & (a<=5)] = 0
a

array([1, 2, 0, 0, 0, 6, 7, 6, 0, 0, 0, 2, 1])

#### - Utilisation de quelques fonctions :

In [211]:
#np.where()
np.where(a>5)

(array([5, 6, 7], dtype=int64),)

In [212]:
#np.nonzero()
np.nonzero(a>5)

(array([5, 6, 7], dtype=int64),)

In [231]:
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [238]:
b[b < 5] = 0 
b

array([0, 0, 0, 0, 5, 6, 7, 6, 5, 0, 0, 0, 0])

In [239]:
b[b >= 5] = 1
b

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [228]:
np.where(a>=5, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [232]:
b[b<2] = 2 
b

array([2, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 2])

In [234]:
b[b>5] = 5
b

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

In [235]:
np.clip(a, 2, 5)

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

In [241]:
np.where(a>5)[0] 

array([5, 6, 7], dtype=int64)

In [242]:
np.nonzero(a>5)[0]

array([5, 6, 7], dtype=int64)

###### - NB : Notez que np.where avec un argument renvoie un tuple de tableaux (1-tuple dans le cas 1D, 2-tuple dans le cas 2D, etc.), (idem pour np.nonzero)

#### - Opérations vectorielles : 
Il existe plusieurs opérateurs : 

In [321]:
#Addition
print(np.array([4, 2]) + np.array([1, 5]))
#Soustraction
print(np.array([4, 2]) - np.array([1, 5]))
#Multiplication
print(np.array([4, 2]) * np.array([1, 5]))
#Division réelle dont le quotient et le reste sont réelles
print(np.array([4, 2]) / np.array([1, 5]))
#division entière dont le quotient et le re#ste sont entières
print(np.array([4, 2]) // np.array([1, 2]))
#Elévation en puissance ou exposant
print(np.array([4, 2])**3)

[5 7]
[ 3 -3]
[ 4 10]
[4.  0.4]
[4 1]
[64  8]


#### - Remarque : 
La plupart des fonctions mathématiques ont des homologues NumPy qui peuvent gérer des vecteurs :

In [257]:
#La racine carrée
print(np.sqrt([9, 4]))
#L'exponantielle
print(np.exp([1, 2]))
#Le logarithme
print(np.log([2, 5]))

[3. 2.]
[2.71828183 7.3890561 ]
[0.69314718 1.60943791]


##### Le produit scalaire et le produit vectorielle ont leurs propres opérateurs :

In [250]:
#Produit scalaire
np.dot([1,2],[3,4])

11

In [262]:
#Produit vectorielle
np.cross([3, 2, 6], [11, 7, 5])

array([-32,  51,  -1])

##### Quelques fonction trigonométriques :

In [263]:
np.sin([np.pi, np.pi/2])

array([1.2246468e-16, 1.0000000e+00])

In [264]:
np.arcsin([0, 1])

array([0.        , 1.57079633])

In [270]:
np.arctan([0, 1])

array([0.        , 0.78539816])

In [271]:
np.arctan2([0, 1], [1, 0])

array([0.        , 1.57079633])

##### Les tableaux peuvent être arrondis dans leur ensemble, on a au moins trois fonctions : 

In [280]:
#np.floor() arrondit à -∞
print(np.floor([1.4, 1.5, 1.9, 2.5]))
#np.ceil() arrondit à +∞ 
print(np.ceil([1.1, 1.4, 1.9, 2.5]))
#np.round() = np.around() arrondit en excès à l'entier le plus proche ( à partir de 0,5)
print(np.round([1.4, 1.5, 1.9, 2.5]))
print(np.around([1.4, 1.5, 1.9, 2.5]))

[1. 1. 1. 2.]
[2. 2. 2. 3.]
[1. 2. 2. 2.]
[1. 2. 2. 2.]


##### Fonctions statistiques de base :  

In [290]:
a = np.random.randint(0, 20, 7)
a

array([ 2, 11, 15,  4,  8, 13,  8])

In [295]:
#Fonction de calcul du maximum np.max() ou tab.max() (tab est un tableau)
print("Le maximum du tableau a est : ",a.max())
#Fonction de recherche l'indexe du maximum argmax()
print("Indexe du maximum du tableau a est : ",a.argmax())
#Fonction de calcul du minimum tab.min()
print("Le minimum du tableau a est : ",a.min())
#Fonction de recherche l'indexe du minimum argmin()
print("Indexe du minimum du tableau a est : ",a.argmin())
#Fonction de calcul de somme tab.sum()
print("La somme des éléments du tableau a est : ",a.sum())
#Fonction de calcul de la variance tab.var()
print("La variance du tableau a est : ",a.var())
#Fonction de calcul de la moyenne tab.mean()
print("La moyenne du tableau a est : ",a.mean())
#Fonction de calcul de l'écart-type tab.std()
print("Ecart-type du tableau a est : ",a.std())

Le maximum du tableau a est :  15
Indexe du maximum du tableau a est :  2
Le minimum du tableau a est :  2
Indexe du minimum du tableau a est :  0
La somme des éléments du tableau a est :  61
La variance du tableau a est :  18.775510204081634
La moyenne du tableau a est :  8.714285714285714
Ecart-type du tableau a est :  4.333071682315172


##### la correction de Bessel  sur l'écart-type : 

In [300]:
a = np.arange(1,4)
a

array([1, 2, 3])

In [311]:
print("Ecart-type : ",a.std())
#Fonction utilisant le correctif de Bessel
print("Ecart-type avec le correctif de Bessel : ",a.std(ddof = 1))
#La fonction std() utilise la correction de Bessel par défaut dans la bibliothèque Pandas
print("Ecart-type avec la bibliothèque Pandas : ",pd.Series(a.std()))

Ecart-type :  0.816496580927726
Ecart-type avec le correctif de Bessel :  1.0
Ecart-type avec la bibliothèque Pandas :  0    0.816497
dtype: float64


##### Avec une taille d'échantillon croissant la correction du Bessel diminue rapidement 

In [326]:
res1 , res2, res3 = [], [], []
for i in range(10):
    a = np.random.randn(5)
    print("res1 = ",res1.append(a.std()))
    print("res2 = ",res2.append(a.std(ddof = 1)))
    print("res3 = ",res3.append(a.std(ddof = 1.5)))

res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None
res1 =  None
res2 =  None
res3 =  None


In [327]:
print("la moyenne de res1 = ",np.mean(res1))
print("la moyenne de res2 = ",np.mean(res2))
print("la moyenne de res3 = ",np.mean(res3))

la moyenne de res1 =  0.7200491658325623
la moyenne de res2 =  0.8050394409718142
la moyenne de res3 =  0.8606233631304437


### - les fonctions de tris :
Elles ont moins de fonctionnalités que leurs homologues Python.

In [338]:
c = np.random.randint(1, 15, 10)
c

array([ 3,  6, 13,  3,  7, 13, 13,  2,  3, 13])

In [339]:
#En Numpy
print("Le tableau trié est : ",c.sort())
print("Le tableau trié est : ",np.sort(c))

Le tableau trié est :  None
Le tableau trié est :  [ 2  3  3  3  6  7 13 13 13 13]


In [358]:
#En Python
def func(x):
    return x % 5
print("La liste triée est : ",c.sort())
print("La liste triée est : ",sorted(c))
print("La liste triée est : ",sorted(c, key = func))#Classe les élts de la liste selon la valeur modulo calculée

Le tableau trié est :  None
Le tableau trié est :  [2, 3, 3, 3, 6, 7, 13, 13, 13, 13]
Le tableau trié est :  [6, 2, 7, 3, 3, 3, 13, 13, 13, 13]


### - Recherche d'un élément dans un vecteur : 
Contrairement aux listes Python, un tableau NumPy n'a pas de méthode index. La demande de fonctionnalité correspondante est en suspens depuis un certain temps maintenant.

In [452]:
d = np.random.randint(1, 20, 15)
d

array([19, 14, 12, 18, 13,  5,  6, 18,  4,  7,  1, 11, 19,  5, 14])

In [373]:
a1 = [12, 0, 47, 5, 1]
b1 = [2, 14, a1, 2, 16]
b1

[2, 14, [12, 0, 47, 5, 1], 2, 16]

In [476]:
#Permet de trouver l'indice d'une valeur valeur dans le tableau (d==5), 
#premier indice designe la ligne et le deuxième designe la colonne
np.where(d==5)[0][1]

13

In [477]:
#Permet de trouver l'indice d'une valeur dans le tableau (v==18)
f = next((i[0] for i, v in np.ndenumerate(d) if v==18), -1)
f

3

In [480]:
#Permet de trouver l'indice d'une valeur dans le tableau (v==18)
k = np.searchsorted(d, 18)
k

3

### Comparaison des flotteurs : 
#### La fonction np.allclose(a, b) compare des tableaux de flottants avec une tolérance donnée

In [400]:
import math
print("Comparaison1 : ",(0.1 + 0.2) == 0.3)
print("Comparaison2 : ",np.allclose(0.1 + 0.2, 0.3))
print("Comparaison3 : ",math.isclose(0.1 + 0.2, 0.3))

Comparaison1 :  False
Comparaison2 :  True
Comparaison3 :  True


In [401]:
print("Comparaison1 : ",1e-9 == 2e-9)
print("Comparaison2 : ",np.allclose(1e-9, 2e-9))
print("Comparaison3 : ",math.isclose(1e-9, 2e-9))

Comparaison1 :  False
Comparaison2 :  True
Comparaison3 :  False


In [402]:
print("Comparaison1 : ",0.1 + 0.2 - 0.3 == 0)
print("Comparaison2 : ",np.allclose(0.1 + 0.2 - 0.3, 0))
print("Comparaison3 : ",math.isclose(0.1 + 0.2 - 0.3, 0))

Comparaison1 :  False
Comparaison2 :  True
Comparaison3 :  False


## 2. Matrices, les tableaux 2D

### - Fonction d'initialisation des matrices :

In [411]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [412]:
print("Type de la matrice :",a.dtype)
print("Taille de la matrice :",a.shape)

Type de la matrice : int32
Taille de la matrice : (2, 3)


In [416]:
#Fonction np.zero()
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [417]:
#Fonction np.full()
np.full((3, 2), 7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [418]:
#Fonction np.ones()
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [421]:
#Fonction np.empty()
np.empty((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [425]:
#Fonction np.eye()
#np.eye(3, 3) ou
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### - Fonction de génération de matrices aléatoires :

In [429]:
#Fonction random.randint()
np.random.randint(0, 10, (3, 2))

array([[9, 1],
       [7, 6],
       [6, 1]])

In [430]:
#Fonction random.rand()
np.random.rand(3, 2)

array([[0.32376403, 0.1791637 ],
       [0.02526515, 0.63871483],
       [0.1113989 , 0.30117289]])

In [431]:
#Fonction random.randn()
np.random.randn(3, 2)

array([[ 0.32660179,  0.56507959],
       [ 0.82096147,  0.10066832],
       [ 0.19765907, -1.1886563 ]])

In [432]:
#Fonction random.uniform()
np.random.uniform(1, 10, (3, 2))

array([[7.72156278, 2.93905443],
       [3.95428832, 6.29204108],
       [2.37726612, 5.40492602]])

In [433]:
#Fonction random.normal()
np.random.normal(10, 2, (3, 2))

array([[ 8.82598627, 14.82380462],
       [13.65627248,  8.75597344],
       [11.50483194, 12.5506985 ]])

### - Fonction de génération de matrices aléatoires avec un nouveau style :

In [434]:
rng = np.random.default_rng()

In [435]:
rng.integers(1, 10,(3, 2))

array([[1, 5],
       [6, 6],
       [2, 3]], dtype=int64)

In [436]:
rng.random((3, 2))

array([[0.12343954, 0.47375045],
       [0.69507332, 0.38202425],
       [0.47553796, 0.60461083]])

In [437]:
#Même fonction que rng.random() mais de moyenne = 0 et d'écart-type = 1
rng.standard_normal((3, 2))

array([[-0.44747152,  0.30238731],
       [-0.59961532,  0.42847384],
       [-0.39042251, -0.14955102]])

In [438]:
rng.uniform(1, 10,(3, 2))

array([[5.31610113, 5.06652208],
       [5.22564293, 3.21250243],
       [1.49750961, 3.48816692]])

In [439]:
rng.normal(5, 2, (3, 2))

array([[9.0087349 , 5.75487823],
       [7.73344772, 5.16996577],
       [7.68928689, 5.61154794]])

### - Indexation bidimensionnelle :
La syntaxe d'indexation bidimensionnelle est plus pratique que celle des listes imbriquées.

In [441]:
a2 = rng.integers(1, 15,(3, 6))
a2

array([[ 2,  2,  3,  7, 12,  6],
       [11,  1,  8, 12, 14, 14],
       [ 7,  6,  8, 14,  6,  2]], dtype=int64)

In [443]:
print("indexation_1 :",a2[1,2])
print("indexation_2 :",a2[1,:])
print("indexation_3 :",a2[:,2])
print("indexation_4 :",a2[:,1:3])
print("indexation_5 :",a2[-2:,-2:])
print("indexation_6 :",a2[::2,1::2])

indexation_1 : 8
indexation_2 : [11  1  8 12 14 14]
indexation_3 : [3 8 8]
indexation_4 : [[2 3]
 [1 8]
 [6 8]]
indexation_5 : [[14 14]
 [ 6  2]]
indexation_6 : [[ 2  7  6]
 [ 6 14  2]]


### - L'argument de l'axe : 
axis = 0 pour les colonnes et axis = 1 pour les lignes

In [482]:
a3 = rng.integers(1, 7,(3, 3))
a3

array([[4, 4, 3],
       [5, 2, 2],
       [6, 3, 6]], dtype=int64)

In [483]:
a3.sum()

35

In [484]:
a3.sum(axis = 0)

array([15,  9, 11], dtype=int64)

In [485]:
a3.sum(axis = 1)

array([11,  9, 15], dtype=int64)

In [486]:
#Sommation d'Einstein pour une ligne
np.einsum('ij->i', a3)

array([11,  9, 15], dtype=int64)

In [487]:
#Sommation d'Einstein pour une colonne
np.einsum('ij->j', a3)

array([15,  9, 11], dtype=int64)

### - Arithmétique matricielle : 
##### En plus des opérateurs ordinaires (comme +,-,*,/,// et **) qui fonctionnent élément par élément, il existe un opérateur @ qui calcule un produit matriciel.

In [491]:
a3 = rng.integers(1, 7,(2, 2))
a4 = rng.integers(1, 7,(2, 2))
print("La matrice a3 est :",a3)
print("La matrice a4 est :",a4)

La matrice a3 est : [[1 4]
 [1 1]]
La matrice a4 est : [[6 2]
 [6 1]]


In [492]:
a3 + a4

array([[7, 6],
       [7, 2]], dtype=int64)

In [493]:
a3 - a4

array([[-5,  2],
       [-5,  0]], dtype=int64)

In [494]:
a3 * a4

array([[6, 8],
       [6, 1]], dtype=int64)

In [495]:
#produit matriciel (produit scalaire) @
a3 @ a4

array([[30,  6],
       [12,  3]], dtype=int64)

In [496]:
a3 ** a4

array([[ 1, 16],
       [ 1,  1]], dtype=int64)

##### NumPy permet des opérations mixtes entre un vecteur et une matrice, et même entre deux vecteurs.

In [5]:
a5 = np.random.randint(1, 10, (3, 3))
a5

array([[2, 6, 4],
       [6, 9, 4],
       [4, 4, 4]])

In [7]:
b1 = np.array([9])
b2 = np.array([-1, 0, 1])
b3 = np.random.randint(1, 10, (3, 1))
print("La matrice b1 :",b1)
print("La matrice b2 :",b2)
print("La matrice b3 :",b3)

La matrice b1 : [9]
La matrice b2 : [-1  0  1]
La matrice b3 : [[6]
 [2]
 [6]]


In [61]:
a6 = np.array([[1, 2, 3]])
b4 = np.array([[1], [2], [3]])
print("La matrice a6 :",a6)
print("La matrice b4 :",b4)

La matrice a6 : [[1 2 3]]
La matrice b4 : [[1]
 [2]
 [3]]


In [37]:
#Division
a5 / b1 

array([[0.22222222, 0.66666667, 0.44444444],
       [0.66666667, 1.        , 0.44444444],
       [0.44444444, 0.44444444, 0.44444444]])

In [25]:
#Multiplication
a5 * b2

array([[-2,  0,  4],
       [-6,  0,  4],
       [-4,  0,  4]])

In [10]:
a5 / b3 

array([[0.33333333, 1.        , 0.66666667],
       [3.        , 4.5       , 2.        ],
       [0.66666667, 0.66666667, 0.66666667]])

In [18]:
a6 * b4

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [21]:
#Inner product (produit intérieur)
a6 @ b4

array([14])

In [62]:
#Outer product (produit extérieur)
b4 @ a6

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

##### Transposition de matrice

In [67]:
c1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Avant transposition :\n",c1, end ='\n\n')
print("Après transposition :\n",c1.transpose())

Avant transposition :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Après transposition :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [68]:
c2 = np.array([[1, 2, 3]])
print("Avant transposition :\n",c2, end ='\n\n')
print("Après transposition :\n",c2.transpose())

Avant transposition :
 [[1 2 3]]

Après transposition :
 [[1]
 [2]
 [3]]


##### Ici, l'argument -1 indique de calculer automatiquement l'une des tailles de dimension et None entre crochets sert de raccourci pour np.newaxis, ce qui ajoute un axe vide à l'endroit désigné.

In [92]:
a = np.arange(1, 7)
print("Tableau 1D :\n",a)

Tableau 1D :
 [1 2 3 4 5 6]


In [93]:
#a.reshape(1, -1) ou
#a[None, :] ou 
print("Vecteurs lignes 2D :\n",a[np.newaxis, :])
aL = a[np.newaxis, :]

Vecteurs lignes 2D :
 [[1 2 3 4 5 6]]


In [94]:
#[:, None] ou
#a.reshape(-1, 1) ou
print("Vecteurs colonnes 2D :\n",a[:, np.newaxis])
aC = a[:, np.newaxis]

Vecteurs colonnes 2D :
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [95]:
#aC.rashape(-1) ou
#np.ravel(aC) ou
print("Vecteurs colonnes 2D -> Tableau original :\n",aC.flatten())

Vecteurs colonnes 2D -> Tableau original :
 [1 2 3 4 5 6]


In [96]:
#aL.rashape(-1) ou
#aL.flatten() ou
print("Vecteurs lignes 2D -> Tableau original :\n",np.ravel(aL))

Vecteurs lignes 2D -> Tableau original :
 [1 2 3 4 5 6]


In [97]:
#a.reshape(2, 3)
aCL = a.reshape(2, -1)
print("La matrice aCL :\n",aCL)

La matrice aCL :
 [[1 2 3]
 [4 5 6]]


In [98]:
aLC = a.reshape(-1, 2)
print("La matrice aLC :\n",aLC)

La matrice aLC :
 [[1 2]
 [3 4]
 [5 6]]


In [99]:
print("Matrice aLC -> Tableau original :\n",aLC.reshape(-1))
print("Matrice aCL -> Tableau original :\n",aCL.reshape(-1))

Matrice aLC -> Tableau original :
 [1 2 3 4 5 6]
Matrice aCL -> Tableau original :
 [1 2 3 4 5 6]


### - Manipulations matricielles
#### Jointure : Il existe deux fonctions principales pour joindre les tableaux 


In [130]:
a = np.random.randint(1, 13, (3, 4))
b = np.random.randint(1, 9, (2, 4))
c = np.random.randint(1, 7, (3, 2))
print("La matrice a :\n", a, end ='\n\n')
print("La matrice b :\n", b, end ='\n\n')
print("La matrice c :\n", c)

La matrice a :
 [[10  7  5  2]
 [ 3 12  1  3]
 [11  8 11 11]]

La matrice b :
 [[4 5 1 7]
 [4 1 3 7]]

La matrice c :
 [[4 2]
 [6 4]
 [2 4]]


In [146]:
#Jointure verticale (avec les matrices de mêmes colonnes)
aJb = np.vstack((a, b))
aJb

array([[10,  7,  5,  2],
       [ 3, 12,  1,  3],
       [11,  8, 11, 11],
       [ 4,  5,  1,  7],
       [ 4,  1,  3,  7]])

In [147]:
#Jointure horizontale (avec les matrices de mêmes lignes)
aJc = np.hstack((a, c))
aJc

array([[10,  7,  5,  2,  4,  2],
       [ 3, 12,  1,  3,  6,  4],
       [11,  8, 11, 11,  2,  4]])

##### Jointure d'une matrice avec un tableau 1D 

In [140]:
c1 = np.random.randint(1, 4, (3,1))
c2 = np.random.randint(1, 4, (1,4))
print("Vecteur de colonnne c1 :\n", c1, end='\n\n')
print("Vecteur de ligne c2 :\n", c2)

Vecteur de colonnne c1 :
 [[1]
 [2]
 [1]]

Vecteur de ligne c2 :
 [[1 1 3 1]]


In [141]:
#Jointure horizontale (avec les tableaux de mêmes lignes)
np.hstack((a, c1))

array([[10,  7,  5,  2,  1],
       [ 3, 12,  1,  3,  2],
       [11,  8, 11, 11,  1]])

In [142]:
#Jointure horizontale (avec les tableaux de mêmes lignes)
np.column_stack((a, c1))

array([[10,  7,  5,  2,  1],
       [ 3, 12,  1,  3,  2],
       [11,  8, 11, 11,  1]])

In [143]:
#Jointure verticale (avec les tableaux de mêmes colonnes)
np.vstack((a, c2))

array([[10,  7,  5,  2],
       [ 3, 12,  1,  3],
       [11,  8, 11, 11],
       [ 1,  1,  3,  1]])

#### Fractionnement : scinder la jointure 

In [151]:
#fractionnement vertical avec vsplit(nom_jointure, [nbre_d'indice_à_la_verticale])
print("Fractionnement de la jointure aJb :\n", np.vsplit(aJb, [3]))

Fractionnement de la jointure aJb :
 [array([[10,  7,  5,  2],
       [ 3, 12,  1,  3],
       [11,  8, 11, 11]]), array([[4, 5, 1, 7],
       [4, 1, 3, 7]])]


In [152]:
#fractionnement horizontal avec hsplit(nom_jointure, [nbre_d'indice_à_l'horizontale])
print("Fractionnement de la jointure aJc :\n", np.hsplit(aJc, [4]))

Fractionnement de la jointure aJc :
 [array([[10,  7,  5,  2],
       [ 3, 12,  1,  3],
       [11,  8, 11, 11]]), array([[4, 2],
       [6, 4],
       [2, 4]])]


In [153]:
#fractionnement horizontal avec hsplit(nom_jointure, [nbre_indice_à_l'horizontale, fin_indice])
print("Fractionnement de la jointure aJc :\n", np.hsplit(aJc, [3, 4]))

Fractionnement de la jointure aJc :
 [array([[10,  7,  5],
       [ 3, 12,  1],
       [11,  8, 11]]), array([[ 2],
       [ 3],
       [11]]), array([[4, 2],
       [6, 4],
       [2, 4]])]


In [155]:
#fractionnement horizontal avec hsplit(nom_jointure, nbre_d'indice) l'indice maximum est exclus
print("Fractionnement de la jointure aJc :\n", np.hsplit(aJc, 3))

Fractionnement de la jointure aJc :
 [array([[10,  7],
       [ 3, 12],
       [11,  8]]), array([[ 5,  2],
       [ 1,  3],
       [11, 11]]), array([[4, 2],
       [6, 4],
       [2, 4]])]


### - La réplication matricielle : 
 Elle peut être effectuée de deux manières : 
 - tile() agit comme un copier-coller
 - repeat() comme une impression assemblée 

In [156]:
a = np.random.randint(1, 5,(2, 2))
print("la matrice a :\n", a)

la matrice a :
 [[4 1]
 [3 4]]


In [157]:
#Copier-coller de a avec la fonction tile(nom_matrice, (nbre_Ligne, nbre_Colonne))
np.tile(a, (2, 3))

array([[4, 1, 4, 1, 4, 1],
       [3, 4, 3, 4, 3, 4],
       [4, 1, 4, 1, 4, 1],
       [3, 4, 3, 4, 3, 4]])

In [158]:
#Impression assemblée de a avec la fonction repeat(nbre_colonne, axis = 1)
b = a.repeat(3, axis = 1)
b

array([[4, 4, 4, 1, 1, 1],
       [3, 3, 3, 4, 4, 4]])

In [159]:
#Impression assemblée de a avec la fonction repeat(nbre_ligne, axis = 0)
b.repeat(2, axis = 0)

array([[4, 4, 4, 1, 1, 1],
       [4, 4, 4, 1, 1, 1],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4]])

##### Suppression de colonnes et de lignes spécifiques avec la fonction delete()



In [165]:
a = np.random.randint(1, 16,(3, 5))
print("la matrice a :\n", a)

la matrice a :
 [[ 4  5  7  1  1]
 [12 12 11  8  1]
 [ 3  5  8 13 14]]


In [166]:
#suppression de colonnes avec delete(nom_matrice, [i, j], axis = 1) avec i et j des indices de colonnes
np.delete(a, [1, 3], axis = 1)

array([[ 4,  7,  1],
       [12, 11,  1],
       [ 3,  8, 14]])

In [5]:
a = np.random.randint(1, 16,(3, 5))
print("la matrice a :\n", a)

la matrice a :
 [[ 1  6 10  2  6]
 [11  8 10  4 12]
 [15  6  2 14  7]]


In [168]:
#suppression de colonnes alignées de i à j avec delete(nom_matrice, np.s_[i:j], axis = 1)
np.delete(a, np.s_[1:-1], axis = 1)

array([[10,  3],
       [ 2, 12],
       [14, 10]])

In [3]:
a = np.random.randint(1, 16,(3, 5))
print("la matrice a :\n", a)

la matrice a :
 [[11  4  7  7  1]
 [10  3  7 15 12]
 [13  7 11  5  3]]


In [172]:
#suppression de colonnes alignées de i à j avec delete(nom_matrice, slice(i, j), axis = 1)
np.delete(a, slice(1, -1), axis = 1)

array([[ 3, 14],
       [ 6,  8],
       [10, 14]])

In [7]:
#suppression de lignes i avec delete(nom_matrice, num_indice_ ligne, axis = 0)
np.delete(a, 2, axis = 0)

array([[ 1,  6, 10,  2,  6],
       [11,  8, 10,  4, 12]])

##### Insertion de colonnes et de lignes spécifiques avec la fonction insert()

In [8]:
h = np.random.randint(1, 16,(3, 3))
print("la matrice h :\n", h)

la matrice h :
 [[10  2 15]
 [ 2 13  2]
 [ 7  1  8]]


In [9]:
v = np.random.randint(1, 16,(2, 5))
print("la matrice v :\n", v)

la matrice v :
 [[13  3  6  4  5]
 [10  7  3  4 14]]


In [10]:
u = np.random.randint(1, 16,(3, 2))
print("la matrice u :\n", u)

la matrice u :
 [[15  1]
 [ 4 13]
 [13  9]]


In [11]:
w = np.random.randint(1, 16,(3, 3))
print("la matrice w :\n", w)

la matrice w :
 [[5 6 7]
 [3 7 1]
 [9 5 9]]


In [18]:
#Insertion de lignes à l'indice i ou/et j avec la fonction insert(nom_matrice, [i, j], valeur_à_inserée, axis = 0)
np.insert(v, [1, 2], 5, axis = 0)

array([[13,  3,  6,  4,  5],
       [ 5,  5,  5,  5,  5],
       [10,  7,  3,  4, 14],
       [ 5,  5,  5,  5,  5]])

In [19]:
#Insertion de colonnes à l'indice i ou/et j avec la fonction insert(nom_matrice, [i, j], valeur_à_inserée, axis = 1)
np.insert(h, 2, 8, axis = 1)

array([[10,  2,  8, 15],
       [ 2, 13,  8,  2],
       [ 7,  1,  8,  8]])

In [20]:
#Insertion de tableau à l'indice i avec la fonction insert(nom_matrice, [i], tableau_à_inseré, axis = 1)
np.insert(u, [0], w, axis = 1)

array([[ 5,  6,  7, 15,  1],
       [ 3,  7,  1,  4, 13],
       [ 9,  5,  9, 13,  9]])

##### Ajout de colonnes et de lignes spécifiques avec la fonction append() ou coloumn_stack()

In [50]:
t = np.random.randint(1, 16,(3, 5))
print("la matrice t :\n", t)

la matrice t :
 [[ 3  7 10 10 11]
 [ 5  3 12 11  2]
 [13  8 11 10 10]]


In [26]:
#Ajout de colonnes avec la fonction append(nom_matrice, colonne_à_inseré, axis = 1)
np.append(t, np.zeros((3, 2)), axis = 1)

array([[15.,  5.,  9.,  8., 13.,  0.,  0.],
       [ 7., 13.,  3.,  8.,  9.,  0.,  0.],
       [ 7.,  5., 11., 12., 11.,  0.,  0.]])

In [35]:
#Ajout d'une seule colonne avec la fonction colomn_satck(nom_matrice, colonne_à_inseré)
np.column_stack((t, np.zeros(3)))

array([[15.,  5.,  9.,  8., 13.,  0.],
       [ 7., 13.,  3.,  8.,  9.,  0.],
       [ 7.,  5., 11., 12., 11.,  0.]])

In [55]:
#Ajout de ligne avec la fonction append(nom_matrice, ligne_à_inseré, axis = 0)
np.append(t, np.ones((2, 5)), axis = 0)

array([[ 3.,  7., 10., 10., 11.],
       [ 5.,  3., 12., 11.,  2.],
       [13.,  8., 11., 10., 10.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

##### Ajout des valeurs constantes à la ou aux bordures du tableau avec la fonction pad()

In [36]:
p = np.random.randint(1, 16,(2, 3))
print("la matrice p :\n", p)

la matrice p :
 [[14 11  7]
 [ 6  6 13]]


In [47]:
#Ajout de valeur constante (par defaut la valeur est 0) avec la fonction pad(nom_matrice, ((i, j), (k, t)))
#i représente le nbre de chiffres à ajouter en haut
#j représente le nbre de chiffres à ajouter en bas
#k représente le nbre de chiffres à ajouter en gauche
#t représente le nbre de chiffres à ajouter en droite
np.pad(p, ((2, 1), (2, 2)))

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 14, 11,  7,  0,  0],
       [ 0,  0,  6,  6, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [48]:
#Ajout de valeur constante (valeur = 5) avec la fonction pad(nom_matrice, ((i, j), (k, t)), constant_values = 5)
np.pad(p, ((2, 1), (1, 0)), constant_values = 5)

array([[ 5,  5,  5,  5],
       [ 5,  5,  5,  5],
       [ 5, 14, 11,  7],
       [ 5,  6,  6, 13],
       [ 5,  5,  5,  5]])

In [49]:
#Ajout de valeur constante avec la fonction pad(nom_matrice, 1), ajoute à toutes les bordures le chiffre renseigné
np.pad(p, 1)

array([[ 0,  0,  0,  0,  0],
       [ 0, 14, 11,  7,  0],
       [ 0,  6,  6, 13,  0],
       [ 0,  0,  0,  0,  0]])

### - Meshgrids (Grille de maillage)

In [58]:
#La logique de C
a = np.empty((2, 3))
for i in range(2):
    for j in range(3):
        a[i, j] = j-i
print(a)

[[ 0.  1.  2.]
 [-1.  0.  1.]]


In [60]:
#La logique de Python (permet de remplir aléatoirement un tableau suivant la taille ces dimensions)
c = [[(j-i) for j in range(3)] for i in range(2)]
a = np.array(c)
a

array([[ 0,  1,  2],
       [-1,  0,  1]])